# NumPy Quick Notes

NumPy is a python library used for working with arrays.

NumPy was created in 2005 by **Travis Oliphant**.

NumPy stands for **Numerical Python**

NumPy aims to provide any object that is upto 50X faster than traditional Lists

The array object in NumPy is called **ndarray**

NumPy arrays are stored at one continuous place in memory unlike lists

This behavior is called **locality of reference**

NumPy is a Python Library is written partially in Python, but most of the parts that require fast computation are written in C or C++.

# Installing NumPy

In [1]:
pip install numpy

# Basic Example of NumPy Array

In [3]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
import numpy as np

print(np.__version__)

1.21.5


# 0-D Arrays

In [5]:
import numpy as np

arr=np.array(42)
print(arr)

42


# 1-D Array

In [6]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 2-D Array

In [7]:
import numpy as np

arr=np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


# 3-D Array

In [8]:
import numpy as np

arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Number of Dimensions

In [10]:
import numpy as np

a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[1,2],[3,4]])
d=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

print(a)
print(b)
print(c)
print(d)

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

42
[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
0
1
2
3


# Higher Dimensional Arrays

In [15]:
import numpy as np

arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


# Array Indexing

In [32]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr[0],arr[-1])

1 4


In [18]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr[1]+arr[2])

5


# Accessing 2-D Arrays

In [24]:
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[-1][-1])

10


In [25]:
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[-1,-1])

10


# Accessing 3-D Arrays

In [31]:
import numpy as np

arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr[1,0,0])

5


# Slicing Arrays

In [33]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [34]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [35]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# Negative Slicing

In [36]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


# Step

In [37]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [38]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# Slicing 2-D Arrays

In [40]:
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [41]:
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [42]:
import numpy as np

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Datatypes


1. integer - i
2. boolean - b
3. unsigned integer - u
4. float - f
5. complex float - c
6. timedelta - m
7. datetime - M
8. object - O
9. string - S
10. unicode string - U
11. chunk of memory - V

In [43]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [44]:
import numpy as np

arr=np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


# Creating Arrays with a Defined Data Type

In [46]:
import numpy as np

arr=np.array([1,2,3,4],dtype='S')

print(arr,type(arr))
print(arr.dtype)

[b'1' b'2' b'3' b'4'] <class 'numpy.ndarray'>
|S1


In [47]:
import numpy as np

arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Converting Data Type on Existing Arrays

In [48]:
import numpy as np

arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [49]:
import numpy as np

arr=np.array([1.1,2.1,3.1])
newarr=arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [50]:
import numpy as np

arr=np.array([1,0,3])

newarr=arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# NumPy Array Copy Vs View

In [51]:
import numpy as np

arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [52]:
import numpy as np

arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Check if Array Owns its Data

In [53]:
import numpy as np

arr=np.array([1,2,3,4,5])

x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# NumPy Array Shape



In [56]:
import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

(2, 4)


In [58]:
import numpy as np

arr=np.array([1,2,3,4],ndmin=5)
print(arr)

print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


# Reshape from 1-D to 2-D

In [61]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr=arr.reshape(2,6)
print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# Reshape from 1-D to 3-D

In [62]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

neewarr=arr.reshape(2,2,-1)

print(neewarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays

In [66]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# Iterating 1-D Arrays

In [69]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


# Iterating 2-D Arrays

In [70]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [71]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


# Iterating 3-D Arrays

In [67]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [68]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays using nditer()

In [72]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# Iterating Array with Different Data Types

In [73]:
import numpy as np

arr=np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'],op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


# Iterating with Different Step Size

In [74]:
import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


# Enumerated Iteration using ndenumerate()

In [76]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

for idx,x in np.ndenumerate(arr):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


# Joining NumPy Arrays

In [80]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [81]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays using Stack Functions

In [83]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Stacking Along Rows

In [84]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns

In [85]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


# Stacking Along Depth

In [86]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays

In [87]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [88]:
newarr[0]

array([1, 2])

In [89]:
newarr[1]

array([3, 4])

In [90]:
newarr[2]

array([5, 6])

In [91]:
newarr[2][0]

5

In [92]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Splitting 2-D Arrays

In [93]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [94]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [95]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [96]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Arrays

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


# Search Sorted

In [4]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [5]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [6]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# Sorting Arrays

In [7]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [8]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [9]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [10]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtering Arrays

In [11]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [12]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [14]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
